version: '3.8'

services:
  ardusub-control:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_RUN_PORT=8000
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - ardusub-network

networks:
  ardusub-network:
    driver: bridge
